// const bookings = [
//     {
//         id: 1,
//         name: 'Samsung Galaxy F62',
//         time: '08.00 AM - 09.00 AM',
//         // img: img2,
//         price: 20,
//         match: 'samsung',
//         space: 10,
//     },
//     {
//         id: 2,
//         name: ' iPhone 13 Pro',
//         time: '09.00 AM - 10.00 AM',
//         // img: img1,
//         match: 'iPhone',
//         price: 15,
//         space: 8,
//     },
//     {
//         id: 3,
//         name: 'Xiaomi Redmi 10 Prime	',
//         time: '10.00 AM - 11.00 AM',
//         // img: img3,
//         match: 'xiaomi',
//         price: 17,
//         space: 9,
//     },
//     {
//         id: 4,
//         name: 'Realme C11 2021 64GB	',
//         time: '11.00 AM - 12.00 PM',
//         // img: img4,
//         match: 'realme',
//         price: 19,
//         space: 5,
//     },
//     {
//         id: 5,
//         name: 'Xiaomi Redmi Note 11 Pro	',
//         time: '06.00 PM - 07.00 PM',
//         // img: img5,
//         match: 'xiaomi',
//         price: 25,
//         space: 10,
//     },
//     {
//         id: 6,
//         name: ' OnePlus Nord 2 Price',
//         time: '07.00 PM - 08.00 PM',
//         // img: img6,
//         price: 35,
//         match: 'plus',
//         space: 10,
//     },
// ]
// export default bookings